volumes:
  pg_data_youtubeclone:

networks:
  youtube-network:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.198.0.0/16
    driver_opts:
      com.docker.network.bridge.name: br_youtubeclone

services:
  backend:
    container_name: youtubeclone-backend
    build: ./youtubeclone-backend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./youtubeclone-backend:/backend
      - ./youtubeclone-backend/node_modules:/backend/node_modules
      - ./static:/backend/static
      - ./vids:/backend/public/uploads/netgear
      - ./vids:/backend/static/uploads/netgear
    env_file: 
      - ./youtubeclone-backend/.env
    networks:
      - youtube-network
    # environment:
    #   DEBUG: 'true'

  postgres:
    restart: always
    image: postgres:12
    env_file:
      - ./youtubeclone-backend/.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data_youtubeclone:/var/lib/postgresql/data/
      - ./backups:/var/backups

  frontend:
    container_name: youtubeclone-frontend
    build: ./youtubeclone-frontend
    env_file:
      - ./youtubeclone-frontend/.env
    networks:
      - youtube-network
    ports:
      - 5000:5000
    volumes:
      - ./youtubeclone-frontend:/app
      - ./youtubeclone-frontend/node_modules:/app/node_modules