volumes:
  pg_data_youtubeclone:


services:
  backend:
    container_name: youtubeclone-backend
    build: ./youtubeclone-backend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./youtubeclone-backend:/backend
      - ./static:/backend/static
    env_file: 
      - ./youtubeclone-backend/.env
    # environment:
    #   DEBUG: 'true'

  postgres:
    restart: always
    image: postgres:12
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data_youtubeclone:/var/lib/postgresql/data/
      - ./backups:/var/backups

  frontend:
    container_name: frontend
    build: ./youtubeclone-frontend
    env_file:
      - ./youtubeclone-frontend/.env
    networks:
      - youtube-network
    ports:
      - 5000:5000
    volumes:
      - ./youtubeclone-frontend:/app