volumes:
  pg_data_youtubeclone:

networks:
  youtube-network:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.199.0.0/16
    driver_opts:
      com.docker.network.bridge.name: br_youtubeclone

services:
  backend:
    container_name: youtubeclone-backend
    build: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./youtubeclone-backend:/backend
      - ./static:/backend/static
    networks:
      - youtube-network
    env_file: 
      - youtubeclone-backend/.env
      - youtubeclone-frontend/.env
    # environment:
    #   DEBUG: 'true'

  postgres:
    restart: always
    image: postgres:12
    env_file:
      - youtubeclone-backend/.env
    ports:
      - "5432:5432"
    networks:
      - youtube-network
    volumes:
      - pg_data_youtubeclone:/var/lib/postgresql/data/
      - ./backups:/var/backups
